const clone = (value) => JSON.parse(JSON.stringify(value));

const initialStore = {
  platform: {
    cluster: {
      cluster_name: 'eduova_test-cluster',
      engine: 'postgresql',
      host: '127.0.0.1',
      port: 5432,
      strategy: 'single_cluster_multi_database',
    },
    superAdmin: {
      id: 'usr-super-master',
      institution_id: 'platform',
      username: 'superadmin',
      email: 'superadmin@eduova.test',
      first_name: 'Master',
      last_name: 'Operator',
      role: 'super_admin',
      password_hash: null,
      is_active: true,
      god_mode: true,
    },
    superAdmins: [],
    institutions: [
      {
        id: 'test-inst',
        name: 'EDUOVA Academy',
        code: 'EDUOVA',
        education_levels: ['PR', 'JH', 'SH'],
        subscription_plan: 'enterprise',
        status: 'active',
        trial_ends_at: '2026-07-31T23:59:59.000Z',
        monthly_revenue: 12000,
        active_students: 2,
        active_staff: 24,
        modules_enabled: 'all',
        settings: {
          tenant_database: {
            cluster_name: 'eduova_test-cluster',
            database_name: 'eduova_eduova',
            database_user: 'postgres',
            schema_name: 'public',
            provision_status: 'provisioned',
          },
          workspace_profile: {
            label: 'basic_secondary',
            menus: ['admissions', 'students', 'academics', 'attendance', 'finance', 'communication'],
          },
        },
        created_at: '2026-06-01T08:00:00.000Z',
      },
      {
        id: 'inst-growth',
        name: 'North Ridge School',
        code: 'NRS',
        education_levels: ['DC', 'PR'],
        subscription_plan: 'growth',
        status: 'trial',
        trial_ends_at: '2026-07-15T23:59:59.000Z',
        monthly_revenue: 4500,
        active_students: 612,
        active_staff: 51,
        modules_enabled: [
          'admissions',
          'finance',
          'academics',
          'attendance',
          'transport',
          'hostel',
          'timetable',
        ],
        settings: {
          tenant_database: {
            cluster_name: 'eduova_test-cluster',
            database_name: 'eduova_nrs',
            database_user: 'postgres',
            schema_name: 'public',
            provision_status: 'provisioned',
          },
          workspace_profile: {
            label: 'daycare_primary',
            menus: ['admissions', 'students', 'attendance', 'communication', 'transport', 'finance'],
          },
        },
        created_at: '2026-05-11T10:15:00.000Z',
      },
    ],
    auditLogs: [
      {
        id: 'plat-audit-001',
        action: 'CREATE',
        resource_type: 'institution',
        resource_id: 'test-inst',
        actor_name: 'Platform Ops',
        actor_role: 'super_admin',
        created_at: '2026-06-02T10:00:00.000Z',
        summary: 'Onboarded EDUOVA Academy',
      },
    ],
  },
  users: {
    accounts: [
      {
        id: 'usr-admin-001',
        institution_id: 'test-inst',
        email: 'admin@eduova.test',
        phone: '+233200000001',
        role: 'institution_admin',
        first_name: 'Amina',
        last_name: 'Owusu',
        staff_number: 'ADM-001',
        department: 'Administration',
        designation: 'Operations Administrator',
        qualification: 'MBA',
        specialization: 'School Operations',
        employment_type: 'full_time',
        date_joined: '2026-01-10',
        is_active: true,
        status: 'active',
        password_hash: 'redacted',
      },
      {
        id: 'usr-teacher-001',
        institution_id: 'test-inst',
        email: 'teacher@eduova.test',
        phone: '+233200000010',
        role: 'teacher',
        first_name: 'Kojo',
        last_name: 'Addo',
        staff_number: 'TCH-014',
        department: 'Science',
        designation: 'Physics Teacher',
        qualification: 'BSc Physics Education',
        specialization: 'Physics',
        employment_type: 'full_time',
        date_joined: '2026-02-01',
        is_active: true,
        status: 'active',
        password_hash: 'redacted',
      },
    ],
  },
  students: {
    profiles: [
      {
        id: 'stu-001',
        institution_id: 'test-inst',
        parent_id: 'parent-001',
        student_number: 'EDU-2026-0001',
        first_name: 'Elikem',
        last_name: 'Mensah',
        full_name: 'Elikem Mensah',
        class_id: 'cls-001',
        class_name: 'SH 2 Science',
        level_code: 'SH',
        photo_url: null,
        attendance_percent: 94,
        balance_due: 600,
        next_exam: 'Math - Tue 09:00',
      },
      {
        id: 'stu-002',
        institution_id: 'test-inst',
        parent_id: 'parent-001',
        student_number: 'EDU-2026-0002',
        first_name: 'Ama',
        last_name: 'Tetteh',
        full_name: 'Ama Tetteh',
        class_id: 'cls-002',
        class_name: 'PR 5 Gold',
        level_code: 'PR',
        photo_url: null,
        attendance_percent: 97,
        balance_due: 0,
        next_exam: 'English - Thu 10:30',
      },
    ],
    teacherRoster: {
      'cls-001': [
        { id: 'stu-001', student_name: 'Elikem Mensah' },
        { id: 'stu-003', student_name: 'Kojo Arthur' },
        { id: 'stu-004', student_name: 'Yaw Boadi' },
      ],
    },
  },
  finance: {
    invoices: [
      {
        id: 'inv-001',
        institution_id: 'test-inst',
        student_id: 'stu-001',
        student_name: 'Elikem Mensah',
        class_name: 'SH 2 Science',
        invoice_number: 'INV-2026-001',
        total_amount: 2400,
        paid_amount: 1800,
        balance: 600,
        status: 'partial',
        due_date: '2026-06-28',
        items: [{ name: 'Tuition', amount: 2400 }],
      },
      {
        id: 'inv-002',
        institution_id: 'test-inst',
        student_id: 'stu-002',
        student_name: 'Ama Tetteh',
        class_name: 'PR 5 Gold',
        invoice_number: 'INV-2026-002',
        total_amount: 950,
        paid_amount: 950,
        balance: 0,
        status: 'paid',
        due_date: '2026-06-20',
        items: [{ name: 'Tuition', amount: 950 }],
      },
    ],
    payments: [],
    feeStructures: [
      {
        id: 'fee-001',
        institution_id: 'test-inst',
        level: 'PR',
        class_name: 'PR 5 Gold',
        term: 'Term 2',
        items: [{ fee_type: 'Tuition', amount: 950, due_date: '2026-06-20' }],
      },
    ],
  },
  academics: {
    structure: {
      groups: [
        {
          id: 'grp-sh2-sci',
          institution_id: 'test-inst',
          name: 'SH 2 Science',
          code: 'SH2-SCI',
          group_type: 'class',
          level_code: 'SH',
          calendar_type: 'term',
        },
        {
          id: 'grp-l100-cs',
          institution_id: 'test-inst',
          name: 'Level 100 Computer Science',
          code: 'L100-CS',
          group_type: 'level',
          level_code: 'TR',
          calendar_type: 'semester',
        },
        {
          id: 'grp-l200-cs',
          institution_id: 'test-inst',
          name: 'Level 200 Computer Science',
          code: 'L200-CS',
          group_type: 'level',
          level_code: 'TR',
          calendar_type: 'semester',
        },
      ],
      periods: [
        {
          id: 'prd-sh2-term2',
          institution_id: 'test-inst',
          group_id: 'grp-sh2-sci',
          name: 'Term 2',
          sequence: 2,
          calendar_type: 'term',
          status: 'active',
          registration_open: true,
          start_date: '2026-05-06',
          end_date: '2026-08-01',
        },
        {
          id: 'prd-l100-sem1',
          institution_id: 'test-inst',
          group_id: 'grp-l100-cs',
          name: 'Semester 1',
          sequence: 1,
          calendar_type: 'semester',
          status: 'completed',
          registration_open: false,
          start_date: '2026-01-15',
          end_date: '2026-05-30',
        },
        {
          id: 'prd-l100-sem2',
          institution_id: 'test-inst',
          group_id: 'grp-l100-cs',
          name: 'Semester 2',
          sequence: 2,
          calendar_type: 'semester',
          status: 'active',
          registration_open: true,
          start_date: '2026-08-12',
          end_date: '2026-12-18',
        },
        {
          id: 'prd-l200-sem1',
          institution_id: 'test-inst',
          group_id: 'grp-l200-cs',
          name: 'Semester 1',
          sequence: 1,
          calendar_type: 'semester',
          status: 'planned',
          registration_open: false,
          start_date: '2027-01-18',
          end_date: '2027-05-28',
        },
      ],
      offerings: [
        {
          id: 'off-sh2-math',
          institution_id: 'test-inst',
          group_id: 'grp-sh2-sci',
          period_id: 'prd-sh2-term2',
          type: 'subject',
          code: 'MATH-SH2',
          name: 'Core Mathematics',
          credit_hours: null,
          is_core: true,
          prerequisite_codes: [],
          next_offering_codes: [],
        },
        {
          id: 'off-sh2-bio',
          institution_id: 'test-inst',
          group_id: 'grp-sh2-sci',
          period_id: 'prd-sh2-term2',
          type: 'subject',
          code: 'BIO-SH2',
          name: 'Biology',
          credit_hours: null,
          is_core: true,
          prerequisite_codes: [],
          next_offering_codes: [],
        },
        {
          id: 'off-csc101',
          institution_id: 'test-inst',
          group_id: 'grp-l100-cs',
          period_id: 'prd-l100-sem1',
          type: 'course',
          code: 'CSC101',
          name: 'Introduction to Programming',
          credit_hours: 3,
          is_core: true,
          prerequisite_codes: [],
          next_offering_codes: ['CSC201'],
        },
        {
          id: 'off-mth101',
          institution_id: 'test-inst',
          group_id: 'grp-l100-cs',
          period_id: 'prd-l100-sem1',
          type: 'course',
          code: 'MTH101',
          name: 'Algebra for Computing',
          credit_hours: 3,
          is_core: true,
          prerequisite_codes: [],
          next_offering_codes: ['MTH201'],
        },
        {
          id: 'off-csc102',
          institution_id: 'test-inst',
          group_id: 'grp-l100-cs',
          period_id: 'prd-l100-sem2',
          type: 'course',
          code: 'CSC102',
          name: 'Data Structures',
          credit_hours: 3,
          is_core: true,
          prerequisite_codes: ['CSC101'],
          next_offering_codes: ['CSC202'],
        },
        {
          id: 'off-gst102',
          institution_id: 'test-inst',
          group_id: 'grp-l100-cs',
          period_id: 'prd-l100-sem2',
          type: 'course',
          code: 'GST102',
          name: 'Communication Skills',
          credit_hours: 2,
          is_core: true,
          prerequisite_codes: [],
          next_offering_codes: [],
        },
        {
          id: 'off-csc201',
          institution_id: 'test-inst',
          group_id: 'grp-l200-cs',
          period_id: 'prd-l200-sem1',
          type: 'course',
          code: 'CSC201',
          name: 'Object Oriented Programming',
          credit_hours: 3,
          is_core: true,
          prerequisite_codes: ['CSC102'],
          next_offering_codes: [],
        },
      ],
      progression_rules: [
        'K-12 schools can map subjects to classes and terms, while tertiary institutions map courses to levels and semesters.',
        'Students only register offerings attached to their current level/class and active academic period.',
        'Outstanding resits lock progression until the required carry-over courses are registered and cleared.',
      ],
    },
    scores: [],
    reportCards: [
      {
        id: 'rc-001',
        institution_id: 'test-inst',
        student_id: 'stu-001',
        student_name: 'Elikem Mensah',
        class_name: 'SH 2 Science',
        level: 'SH',
        term: 'Term 2',
        overall_average: 78,
        overall_grade: 'A-',
        is_published: false,
        results: [
          { subject: 'Mathematics', score: 82, grade: 'A1' },
          { subject: 'English', score: 74, grade: 'B2' },
          { subject: 'Science', score: 78, grade: 'B2' },
        ],
      },
      {
        id: 'rc-002',
        institution_id: 'test-inst',
        student_id: 'stu-002',
        student_name: 'Ama Tetteh',
        class_name: 'PR 5 Gold',
        level: 'PR',
        term: 'Term 2',
        overall_average: 86,
        overall_grade: 'A',
        is_published: true,
        results: [
          { subject: 'Mathematics', score: 90, grade: 'A' },
          { subject: 'English', score: 84, grade: 'A' },
        ],
      },
    ],
  },
  attendance: {
    sessions: [
      {
        id: 'ses-001',
        institution_id: 'test-inst',
        class_id: 'cls-001',
        class_name: 'SH 2 Science',
        session_type: 'morning',
        status: 'open',
        date: '2026-06-20',
      },
    ],
    records: [],
  },
  timetable: [
    { day: 'Monday', period: '8:00', subject: 'Mathematics', teacher: 'Mr. Addo', room: 'A1' },
    { day: 'Tuesday', period: '10:00', subject: 'Science', teacher: 'Mrs. Aryee', room: 'Lab 1' },
  ],
  transport: {
    vehicles: [
      {
        id: 'veh-001',
        institution_id: 'test-inst',
        vehicle_id: 'veh-001',
        name: 'Bus 1',
        route: 'East Legon Shuttle',
        lat: 5.6037,
        lng: -0.187,
        speed: 32,
        next_stop: 'School Gate',
        eta: '12 mins',
        student_stop: {
          name: 'East Legon Junction',
          lat: 5.6037,
          lng: -0.187,
        },
        updated_at: '2026-06-20T08:00:00.000Z',
      },
    ],
  },
  tertiary: {
    departments: [{ id: 'dep-001', institution_id: 'test-inst', name: 'Computer Science' }],
    programs: [
      { id: 'prog-001', institution_id: 'test-inst', name: 'BSc Computer Science', type: 'degree' },
    ],
    registrations: [],
    studentProgress: [
      {
        student_id: 'usr-tertiary-student-001',
        institution_id: 'test-inst',
        current_group_id: 'grp-l100-cs',
        current_period_id: 'prd-l100-sem2',
        passed_offering_codes: ['CSC101'],
        outstanding_resit_codes: [],
        can_progress: true,
        fee_clearance: true,
      },
      {
        student_id: 'stu-001',
        institution_id: 'test-inst',
        current_group_id: 'grp-l100-cs',
        current_period_id: 'prd-l100-sem2',
        passed_offering_codes: ['CSC101'],
        outstanding_resit_codes: ['MTH101'],
        can_progress: false,
        fee_clearance: true,
      },
    ],
    transcripts: [
      { student_id: 'stu-001', institution_id: 'test-inst', cgpa: 3.62, credit_hours: 45, semester: '2026/1' },
    ],
  },
  daycare: {
    presentNow: [
      { student_id: 'dc-001', student_name: 'Baby Ama', institution_id: 'test-inst', session: 'AM' },
    ],
    milestones: {},
    pickupPins: {},
  },
};

const store = clone(initialStore);

const resetRuntimeStore = () => {
  Object.keys(store).forEach((key) => {
    delete store[key];
  });
  Object.assign(store, clone(initialStore));
};

module.exports = {
  store,
  resetRuntimeStore,
};
